version: 2.1

executors:
  default:
    docker:
      - image: quay.io/hemanth22/rockylinux9:9

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            dnf install -y wget unzip java-1.8.0-openjdk-devel java-11-openjdk-devel
            wget -U "Any User Agent" https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.6.1/gatling-charts-highcharts-bundle-3.6.1-bundle.zip
            unzip gatling-charts-highcharts-bundle-3.6.1-bundle.zip
            java -version
      - run:
          name: Run Gatling Simulation
          command: |
            ls -ltra
            chmod -R 777 gatling-charts-highcharts-bundle-3.6.1
            cp -v CalculatorSimulation gatling-charts-highcharts-bundle-3.6.1/user-files/simulations/
            cp -v CalculatorSimulation gatling-charts-highcharts-bundle-3.6.1/user-files/simulations/computerdatabase/
            cp -v CalculatorSimulation gatling-charts-highcharts-bundle-3.6.1/user-files/simulations/computerdatabase/advanced/            
            gatling-charts-highcharts-bundle-3.6.1/bin/gatling.sh -s CalculatorSimulation

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
