version: 2.1

executors:
  default:
    docker:
      - image: cimg/openjdk:21.0.2

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
            wget -U "Any User Agent" https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.6.1/gatling-charts-highcharts-bundle-3.6.1-bundle.zip
            unzip gatling-charts-highcharts-bundle-3.6.1-bundle.zip
      - run:
          name: Run Gatling Simulation
          command: |
            ls -ltra
            chmod -R 777 gatling-charts-highcharts-bundle-3.6.1/bin/gatling.sh
            gatling-charts-highcharts-bundle-3.6.1/bin/gatling.sh -s CalculatorSimulation

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
